### ISSUE TITLE
Add AppLayout Router

### ISSUE THREAD

**Issue by henry61024** [dashcow/dashcow-web#125]
## TODO

- [ ] Build `AppLayoutRouter` with `AppLayout` with `react-router`
- [ ] Make `AppLayoutRouter`'s route configurable
- [ ] Make sure menu click route can trigger correctly
