### ISSUE TITLE
Fix configs including lint/ignore/versions

### ISSUE THREAD

**Issue by henry61024** [dashcow/dashcow-web#2]
## TODO

- [x] Add more specific rules to `.gitignore`, `.eslintignore`,  `.stylelintignore`, `.prettierignore`
- [x] Enable typescript check to Storybook & ~~Testing-libarary~~
- [x] Close `typescript.validate.enable` & `javacript.validate.enable`
- [x] Upgrade Storybook version
- [x] add Storybook deployer (ghpage)
