### ISSUE TITLE
Add Section related UI Components

### ISSUE THREAD

**Issue by henry61024** [dashcow/dashcow-web#57]
## TODO

- [ ] Section
- [ ] Pie Section (with filter)
- [ ] Chart Section (with filter)
- [ ] Dropdown option for Sections
