### ISSUE TITLE
Extract wrapLink/wrapOnClick Util/Component

### ISSUE THREAD

**Issue by henry61024** [dashcow/dashcow-web#65]
## TODO

- [ ] add `wrapLink` util
- [ ] add `LinkWrapper` component
- [ ] add `wrapOnClick` util
- [ ] add `onClickWrapper` component
