### ISSUE TITLE
Add dashboard basic components

### ISSUE THREAD

**Issue by henry61024** [dashcow/dashcow-web#7]
### Add Components

- [ ] Statistic card (#61)
- [ ] Page Title Header (#55)
- [ ] Overview (#56)
- [ ] Section (#57)
- [ ] Pie section (#57)
- [ ] Chart section (#57)
- [ ] Table (#58)
- [ ] Search bar (#59)
- [ ] Profile (#60)

### Chores

- [ ] Fix TS errors
- [ ] Refactor folder structure
